### ISSUE TITLE
是否可以考虑支持下 ThinkJS

### ISSUE THREAD

**Issue by welefen** [xunuoi/node-bigpipe#1]
ThinkJS 见 https://thinkjs.org/

**Comment by xunuoi** [comment]
可以考虑，整合下ThinkJS的http的write等方法应该可以实现~

**Comment by welefen** [comment]
那帮忙实现个吧，完成后有红包奖励。

**Comment by xunuoi** [comment]
@welefen 恩已经做了对ThinksJS的支持了，文档刚才也更新了

如果在ThinksJS中使用，只需要多传一个this参数，其他用法无变化

let bp = new Bigpipe('thinkBP', http.req, http.res, this)

其他框架如Express不需要传this，因为express的模板渲染方法整合到res对象中了，ThinkJS的渲染模板相关的是this.display和this.assign，所以需要额外多传入一个this。

另外bp.start() 启动的时候也类似ThinkJS，默认参数是index_index.html（仅在ThinksJS中有效）

其他的部分和调用跟文档中相同无变化。

**Comment by xunuoi** [comment]
文档： https://github.com/xunuoi/node-bigpipe

**Comment by welefen** [comment]
赞一个，加我微信吧，给你红包，哈哈^_^。微信号： welefen

**Comment by xunuoi** [comment]
哈哈多谢，红包不用了，这是应该的~加你微信认识一下，结交个新朋友 ：)

**Comment by xunuoi** [comment]
@welefen 对了你是ThinkJS的主要发起人吧，ThinkJS很不错啊，框架天然就支持了ES6，不像Sails那么折腾（Sails近期估计快玩完了，后续可能没啥维护了）。 另外赶脚在controller中，有关渲染模板和数据的方法，assign和display等，也就是this的一些方法，可以考虑继承Express/Sails的风格，整合到res对象中，甚至取消this这个对象，就通过传参传入req，res等。我觉着这样做的好处除了更加api调用简洁外，主要是跟传统Node 的web框架更加一致，会有更多人愿意尝试从而容易扩大。现在ThinkJS的风格可能对后端JAVA/PHP等童鞋很熟悉和友好，对传统写Node或者前端js过来的可能有些陌生。如果跟传统node web保持一致，我觉着ThinkJS推广起来肯定会更加牛逼，比如那个display方法如果改成render，估计很多用过express/sails童鞋一眼看到就知道，哦，这个一定就是渲染模板的方法了
纯粹个人看法哈，看好ThinkJS，现在Sails已经更新很慢了，不太敢指望了。
希望ThinkJS越来越好、开发者越来越多！

**Comment by welefen** [comment]
多谢建议，后续可以考虑。 

有其他建议欢迎到 https://github.com/75team/thinkjs/issues 提 issue

**Comment by xunuoi** [comment]
OK~~
