### ISSUE TITLE
能把package.json 的依赖包添加上？

### ISSUE THREAD

**Issue by xmllein** [xunuoi/node-bigpipe#2]

**Comment by xunuoi** [comment]
@xmllein 
 是说Promise么，这个组件写的时候默认是在es6环境下的适配，所以低版本当时没做兼容。写的时候用的Nodejs内置的Promise，在低版本nodejs上可能会没有Promise支持。

我转了一份es5的代码，作为默认调用的脚本了。稍后再考虑补充下Promsie的库到里面做低版本适配～

多谢提醒 :)
